title: iWriteHere
name: 'happy❤learning'
author: Rahul Bakshee
description: happy❤learning
site_url: 'https://github.com/rahulbakshee/iWriteHere'
baseurl: "/iWriteHere"
profile_url: "https://rahulbakshee.github.io"

twitter:
  username: rahulbakshee
  card: summary
  
# Email and twitter are optional:
# youtube_username: UCjZ09Tf8WvvsYoHmDZWsWBQ
# twitter_username: rahulbakshee
# github_username: rahulbakshee
# linkedin_username: rahulbakshee

# Set this to true to get LaTeX math equation support
use_math: true

# Add your Google Analytics ID here if you have one and want to use it
google_analytics: UA-180649952-1

# Everything below here can be ignored, unless you want to change the theme entirely
theme: minima
plugins:
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap

# titles_from_headings:
#  enabled:     true
#   strip_title: true
#   collections: true
  
highlighter: rouge
markdown: kramdown
excerpt_separator: <!--more-->
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
